[lesson 18]
MotorinaLidiya/test-guru pull request #17
Opened 2024-10-08 14:37 UTC by MotorinaLidiya

2024-10-08 17:17 UTC, VidgarVii requested changes

2024-10-08 17:17 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      # TestsMailer.completed_test(@test_passage).deliver_now if @test_passage.result_successful?
не совсем понятно зачем это в ПР?

2024-10-08 17:17 UTC, VidgarVii commented on app/models/test_passage.rb
> +  after_update :reward_badges, if: :completed?
строить логику на колбеках очень плохая идея. Колбеки это всегда не ожидаемое поведение. И работать с ними очень сложно.

2024-10-08 17:17 UTC, VidgarVii commented on app/models/test_passage.rb
> +  end
Теперь модель стала божественна. Это антипаттерн, который нарушает закон Деметры. Чтобы проект не превратился в кашу без четкой распределенной ответственности, в моделях надо оставить код только для работы с данными из собственной таблицей. Результаты теста ну ни как не могут отвечать за выдачу баджа. Им даже про это знать не надо. Место бизнес логике в сервисах. А сервисы могут вызывать либо контроллеры либо другие сервисы

2024-10-08 17:17 UTC, VidgarVii commented on app/models/badge.rb
> +end
оставил коммент в модельке TestPassage, который относится и к этой модели. И еще вопрос. ЧТо будет с этим классом когда надо будет добавить еще 10к правил. А правил может быть сотни. Проекты с подобной системой вознаграждения имеют несколько сотен ачивок

2024-10-08 19:48 UTC, MotorinaLidiya commented on app/controllers/test_passages_controller.rb
> +      # TestsMailer.completed_test(@test_passage).deliver_now if @test_passage.result_successful?
Забыла с Mailer комментарий снять, скрывала чтобы не мешал

2024-10-10 07:25 UTC, VidgarVii requested changes

2024-10-10 07:25 UTC, VidgarVii commented on app/controllers/admin/categories_controller.rb
> +end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-10-10 07:25 UTC, VidgarVii commented on app/models/test_passage.rb
> +  def reward_badges
как я уже писал. данной модели не надо знать ни чео о баджах и сервисах. 
Баджы выдаются после завершения теста. Тест завершается в контроллере. И вот обязанность контроллера делегировать логику другим классам. И контроллер уже может знать о всех моделей и сервисах

2024-10-10 07:25 UTC, VidgarVii commented on app/services/badges/failed_3_tests.rb
> +module Badges
отличное решение!

2024-10-10 07:25 UTC, VidgarVii commented on app/models/badge.rb
> +  def reward?(test_passage, user)
вот эту логику лучше убрать из модели и перенсти в сервис. Так же тут можно сильно упростить код используя полиморфизм и табличный метод

2024-10-11 13:05 UTC, merged